/**
 * Centralised Error Handler — catches errors thrown (or next(err))
 * from any route and returns a safe, sanitised JSON response.
 *
 * Security: NEVER exposes raw err.message to the client — that could
 * leak SQL constraints, file paths, or stack internals. Only known
 * error types (ValidationError, etc.) reveal detail; everything else
 * returns a generic "Internal server error".
 *
 * Logging: The real error is written to the structured logger with the
 * request ID attached (set by requestLogger middleware).
 */

const logger = require('../lib/logger');

/**
 * Express error-handling middleware (4 params)
 * @param {Error} err
 * @param {Object} req
 * @param {Object} res
 * @param {Function} next
 */
module.exports = (err, req, res, next) => {
  // Always log the real error server-side for debugging, correlated
  // with the request ID generated by requestLogger.
  const meta = {
    ...logger.errMeta(err),
    requestId: req.requestId || res.locals.requestId,
    method: req.method,
    path: req.originalUrl,
  };
  logger.error('Request error', meta);

  // Known / safe errors — expose detail to the client
  if (err.name === 'ValidationError') {
    return res.status(400).json({ error: err.message, fieldErrors: err.fieldErrors || undefined });
  }
  if (err.name === 'UnauthorizedError' || err.code === 'UNAUTHORIZED') {
    return res.status(401).json({ error: 'Unauthorized' });
  }
  if (err.name === 'ForbiddenError') {
    return res.status(403).json({ error: 'Forbidden' });
  }
  if (err.name === 'NotFoundError') {
    return res.status(404).json({ error: err.message });
  }

  // Everything else — generic message, no internals leaked
  const status = err.status || 500;
  res.status(status).json({
    error: status === 500 ? 'Internal server error' : err.message,
  });
};
